### ISSUE TITLE
CTA button text is not accessible 

### ISSUE THREAD

**Issue by AmineAouragh** [Njong392/Abbreve#19] opened 2022-10-03 17:07 UTC
### Description

Hey! 

I would like to share that the text on the CTA button "find an abbreviation" changes its color on click and it becomes not accessible. Not enough contrast between the text-color and bg-color. 

I would rather keep the text color white.

### Screenshots

![Screenshot_20221003-180611_Samsung Internet](https://user-images.githubusercontent.com/71039249/193636785-e7e1dc70-23c9-4b56-b1bc-15f914ce3e1c.jpg)

**Comment by Njong392** [comment] 2022-10-03 17:21
This is also being worked on. I used the `react-scroll` package that comes with `Link` and styling the link attribute itself is kind of messy. I 'll look into this though.

**Comment by Njong392** [comment] 2022-10-04 06:51
This issue is sort of a duplicate of #16 so I'll close it.

**Closed by Njong392** 2022-10-04 06:51 UTC
Labels: bug
